### ISSUE TITLE
Function returns invalid pointer

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qtermwidget#238] opened 2019-01-05 14:44 UTC
1. QByteArray tmp is a stack variable https://github.com/lxqt/qtermwidget/blob/f475050f38497debd1b5ceb6b671089849bd8396/lib/kptydevice.h#L253
2. Its method returns data that is stored in `ptr`
https://github.com/lxqt/qtermwidget/blob/f475050f38497debd1b5ceb6b671089849bd8396/lib/kptydevice.h#L255
3. ptr is returned from the function after local variable tmp is destroyed. This is potentially causing problems
https://github.com/lxqt/qtermwidget/blob/f475050f38497debd1b5ceb6b671089849bd8396/lib/kptydevice.h#L259
One more problem is: I do not understand the code logic
```
QByteArray tmp;
tmp.resize(qMax(CHUNKSIZE, bytes));
ptr = tmp.data();
```
`tmp` is neither assigned nor modified
So I really wonder what **should** be returned here. Hope someone helps :)

**Comment by yan12125** [comment] 2019-01-05 14:49
Sounds like a bug. Need to check how similar sections do in kpty.

**Comment by shlyakpavel** [comment] 2019-01-05 14:54
@yan12125 the same code there
https://github.com/KDE/kpty/blob/f3353d84ec0da13847e15685856a2a255025e40d/src/kptydevice.cpp#L136

**Comment by yan12125** [comment] 2019-01-05 15:00
Thanks. I wonder why they wrote such code...

**Comment by yan12125** [comment] 2019-01-07 06:57
OK this is not a bug but a Qt magic. In the following line:
```
buffers << tmp;
```
The KRingBuffer class member `buffers` increases the reference count for `tmp`, so its internal data is not deallocated when the variable `tmp` is out of scope.

I prefer not to touch the piece of code unless there are real issues. Playing with Qt memory management is not easier than playing with fire.

**Closed by yan12125** 2019-01-07 06:57 UTC
Labels: bug
